### ISSUE TITLE
Lifting of exception blocks

### ISSUE THREAD

**Issue by mshinwell** [ocaml-flambda/ocaml#166]

**Comment by lthls** [comment]
With #161 merged, all that remains is deciding on a flag for enabling or disabling this.
A good default might be to allow lifting of exception blocks (or unique blocks in general, though currently only the exception blocks are unique), but rely on `reify_continuation_param_types` for other blocks to prevent lifting too much.

**Comment by lthls** [comment]
#184 introduces a flag that controls the new lifting.
