### ISSUE TITLE
Write up new ideas about lifting

### ISSUE THREAD

**Issue by mshinwell** [ocaml-flambda/ocaml#214]

**Comment by chambart** [comment]
There are a few things that can't be lifted right now: Only things that can be reinfied can be lifted since lifting is done through reification. This means that 2 things can't be assigned symbols: unknown values and immediates:

```OCaml
let n = if Random.bool () then 1 else 2
let f x = x + n
```
```OCaml
let b = Sys.opaque_identity (1, 2)
let g () = fst b
```
Hence both `f` and `g` ends up not closed while they would have been in closure of flambda1
The source level equivalent of the required transformation to fix that would be

```OCaml
type 'a t = { v : 'a }
let n = if Random.bool () then 1 else 2
let n = { v = n }
let f x = x + n.v
```
```OCaml
let b = Sys.opaque_identity (1, 2)
let b = { v = b }
let g () = fst b.v
```
This is the equivalent of what flambda1 does in `Lift_let_to_initialize_symbol`

We can choose 2 ways to fix that right now:
* The 'somewhat quick and dirty' way would be to mimick closure by lifting only what is toplevel in the source. This would be quite easy to do during cps-conversion.
* A more complete version would allow to lift in situations like:
```OCaml
let f x =
  let () = ignore () in (* Just so that this is compiled as two unary functions *)
  let g = fun y -> x + y in
  g

let h = (f [@inlined]) (Sys.opaque_identity 1)
```
With the source level version `g` after inlining f wouldn't be closed as x couldn't be assigned a symbol.
The same transformation could be applied during simplify when an expression is toplevel. I foresee 2
implementations for that. The naïve way I quickly tried and seems to be 'ok' is to do the transformation
for every toplevel expression and add to dacc a substitution map:

```
let k x =
  expr
  (fun ... -> ... x_from_closure ...)  { x_from_closure = x }
```
```
let k x =
  let x' = Makeblock x in
  expr
  (fun ... ->
    let x_from_closure = GetField x' in
    ... x_from_closure ...)
   { empty_closure }
```
That map would contain { x => x' } and when simplifying a function using x we introduce at the beginning a projection from x' instead.
This map need some careful renaming to handles properly nested functions. But nothing too complex
```
let k x =
  expr
  (fun ... ->
      { g : (fun ... -> ... x_from_closure_from_closure)
        { x_from_closure_from_closure = x_from_closure ... })
   { x_from_closure = x }
```
The main problem I see is more esthetic: This feel like some duplication of the alias map.

The other way that would I think quite well suit the current status of flambda is to encode that renaming as an alias. For that we would need to extend the `Name.t` of `Symbol.t` type to represent projections from symbols. Adding just that this kind of symbol is also prefered to a variables would do the trick. The generated Cmm might contain some redundancy but this would be eliminated by mach level CSE and would reduce spilling.

**Comment by lpw25** [comment]
I am still not clear on *why* you would want to lift in these cases:
```ocaml
let n = if Random.bool () then 1 else 2
let f x = x + n

let b = Sys.opaque_identity (1, 2)
let g () = fst b
```
If you don't lift then the value gets stored in the statically allocated closure, which is no different that it being stored in some other statically allocated block.

In flambda 1, this was not the case -- the closure would not be statically allocated and so there was a benefit to lifting the values out. However, with flambda 2 the benefit is much less obvious.

**Comment by chambart** [comment]
Yes certainly... Let's forget about this.

**Comment by chambart** [comment]
Ah I found again what was the problem. It involves situations that are a bit more complex:
```OCaml
let v = Sys.opaque_identity 33

let g () =
  let () = ignore () in
  let f x = x + v in
  f
```
`g` being evaluated only once has no problem being lifted. But this is not the case for `f` here. It cannot be statically allocated with a field in the closure to be produced at runtime. One could try to show that there is a single potential value `v`, hence it would be kind of ok as a let symbol. But that would diverge quite a lot from the way let symbols are allowed right now.

**Comment by lpw25** [comment]
That example is more interesting. I don't think that creating an additional symbol to hold `v` is the right approach for it though.

Written out after closure conversion with some made-up syntax that is hopefully intuitive, I think your example should be something like:
```ocaml
let v = Sys.opaque_identity 33

let g (env = {v = v}) () =
  let () = ignore () in
  let v' = env.v in
  let f (env = {v = v'}) x = x + env.v in
  f
```
so the closure of `f` is populated from the closure parameter of `g`. Then, when `g` is lifted, it's closure is replaced with a symbol and you get:
```ocaml
let v = Sys.opaque_identity 33

let g (env = g_env) () =
  let () = ignore () in
  let v' = g_env.v in
  let f (env = {v = v'}) x = x + env.v in
  f
where g_env = { v = v }
```
And here I think we currently get stuck. However, we don't really need to create a new block to hold `v` -- it is already available in `g_env`. 

One option is to try to replace the access through `f`s closure with an access through  `g`s closure in `g_env`:
```ocaml
let v = Sys.opaque_identity 33

let g (env = g_env) () =
  let () = ignore () in
  let v' = g_env.v in
  let f (env = {}) x = x + g_env.v in
  f
where g_env = { v = v }
```
which would then allow `f` to be lifted. I don't think the current CSE code will do this, but that is where I would probably look to make this transformation happen.

Alternatively, we could observe that whilst `g_env.v` is not a constant, it is a pure expression built entirely out of constants, and so `f` can still be lifted to something like:
```ocaml
let v = Sys.opaque_identity 33

let g (env = g_env) () =
  let () = ignore () in
  f
and f (env = f_env) () = x + f_env.v
where g_env = { v = v }
and f_env = { v = g_env.v }
```
This would probably require `refiy` to notice that the value of the closure was available through `g_env.v` -- probably via the CSE tables.

**Comment by mshinwell** [comment]
I've got this example working using the "symbol projections" method.  This tracks variables that are known to be equal to projections from symbols.  When such variables are used in the construction of a lifted constant, the projections are noted down too, and then examined when the constant is placed.  This placement happens after the grouping of constants into recursive groups (which is required since lifting may introduce more recursion) has happened.  This means that we can determine whether a projection is from a symbol in the group of constants currently being placed.  If it is, the projection can be evaluated by the simplifier to yield a `Simple`.  Otherwise a `Project_var` or `Block_load` is inserted.  This neatly sidesteps the potential problem of knowing where to insert the projection if we're dealing with the same set.

```
After simplify:
((module_symbol Symbol_projections2.camlSymbol_projections2)
 (return_continuation k10) (exn_continuation k2)
 (let_symbol
  ▶ camlSymbol_projections2__ignore_0_0_code =
  ((newer_version_of ()) (stub false) (inline Never_inline)
   (is_a_functor false) (params_arity 𝕍) (result_arity 𝕍)
   (recursive Non_recursive) Deleted)
  ▶ camlSymbol_projections2__anon-fn[symbol_projections2.ml:11,8--17]_2_2_code =
  ((newer_version_of ()) (stub false) (inline Default_inline)
   (is_a_functor false) (params_arity 𝕍=tagged_ℕ𝕚) (result_arity 𝕍=tagged_ℕ𝕚)
   (recursive Non_recursive) Deleted)
  ▶ camlSymbol_projections2__g_1_1_code =
  ((newer_version_of ()) (stub false) (inline Default_inline)
   (is_a_functor false) (params_arity 𝕍) (result_arity 𝕍)
   (recursive Non_recursive) Deleted)
  ▶ camlSymbol_projections2__ignore_0_3_code =
  ((newer_version_of camlSymbol_projections2__ignore_0_0_code) (stub false)
   (inline Never_inline) (is_a_functor false) (params_arity 𝕍)
   (result_arity 𝕍) (recursive Non_recursive)
   (λ〈k47〉《k48》(param/143 ∷ 𝕍) (my_closure/144 ∷ 𝕍) . return k47 0)))
  ▶ Symbol_projections2.camlSymbol_projections2__ignore_3 ↤ ignore/0 =
  (set_of_closures
   ({(ignore/0
      ((code_id camlSymbol_projections2__ignore_0_3_code)
       (dbg symbol_projections2.ml:5,26--32) (is_tupled false)))}))
  (let
   (v/145 = ((Opaque_identity 33) <symbol_projections2.ml:7,8--26>)
    v/146 = v/145)
   (let_symbol
    ▷ Symbol_projections2.camlSymbol_projections2__g_4 ↤ g/1 =
    (set_of_closures
     ({(g/1
        ((code_id camlSymbol_projections2__g_1_4_code)
         (dbg symbol_projections2.ml:9,6--59) (is_tupled false)))})
     (env {(v/1 v/145)}))
    and Symbol_projections2.camlSymbol_projections2__anon-fn[symbol_projections2.ml:11,8--17]_5 ↤ anon-fn[symbol_projections2.ml:11,8--17]/2 =
    (set_of_closures
     ({(anon-fn[symbol_projections2.ml:11,8--17]/2
        ((code_id
          camlSymbol_projections2__anon-fn[symbol_projections2.ml:11,8--17]_2_5_code)
         (dbg symbol_projections2.ml:11,8--17) (is_tupled false)))})
     (env {(v/2 v/146)}))
    and camlSymbol_projections2__anon-fn[symbol_projections2.ml:11,8--17]_2_5_code =
    ((newer_version_of
      camlSymbol_projections2__anon-fn[symbol_projections2.ml:11,8--17]_2_2_code)
     (stub false) (inline Default_inline) (is_a_functor false)
     (params_arity 𝕍=tagged_ℕ𝕚) (result_arity 𝕍=tagged_ℕ𝕚)
     (recursive Non_recursive)
     (λ〈k49〉《k50》(x/147 ∷ 𝕍=tagged_ℕ𝕚) (my_closure/148 ∷ 𝕍) .
      (let
       (v/149 =
         (((Project_var (anon-fn[symbol_projections2.ml:11,8--17]/2 v/2))
           Symbol_projections2.camlSymbol_projections2__anon-fn[symbol_projections2.ml:11,8--17]_5))
        Paddint/150 = ((+ x/147 v/149) <symbol_projections2.ml:11,12--17>))
       return k49 Paddint/150))))
    and camlSymbol_projections2__g_1_4_code =
    ((newer_version_of camlSymbol_projections2__g_1_1_code) (stub false)
     (inline Default_inline) (is_a_functor false) (params_arity 𝕍)
     (result_arity 𝕍) (recursive Non_recursive)
     (λ〈k51〉《k52》(param/151 ∷ 𝕍) (my_closure/152 ∷ 𝕍) .
      ((apply
        ((Symbol_projections2.camlSymbol_projections2__ignore_3〈k54〉《k52》
          (0))
         (call_kind
          (Direct (code_id camlSymbol_projections2__ignore_0_3_code)
           (closure_id ignore/0) (return_arity 𝕍)))
         (dbg symbol_projections2.ml:10,11--20) (inline Default_inline)
         (inlining_depth 0)))
       k54 (param/153 ∷ 𝕍): goto k53
       k53:
        return k51 Symbol_projections2.camlSymbol_projections2__anon-fn[symbol_projections2.ml:11,8--17]_5))))
    ▷ Symbol_projections2.camlSymbol_projections2__Pmakeblock112 =
    (Immutable_block (tag 0)
     (Symbol_projections2.camlSymbol_projections2__ignore_3 v/145
     Symbol_projections2.camlSymbol_projections2__g_4))
    ▶ Symbol_projections2.camlSymbol_projections2 =
    (Immutable_block (tag 0)
     (Symbol_projections2.camlSymbol_projections2__ignore_3 v/145
     Symbol_projections2.camlSymbol_projections2__g_4))
    module_init_end k10 Symbol_projections2.camlSymbol_projections2))))
```

**Comment by mshinwell** [comment]
Two notes on the above:
- Some constants may be grouped together (because they used to involve symbol projections between themselves) even though they aren't recursive in the end.  This is done to make things more efficient during constant sorting, but should be of no consequence.
- There's an extraneous "variable = variable" let-binding, but this happens sometimes (just like inlining continuations), since you can't use permutations to do non-fresh substitutions.
