### ISSUE TITLE
Deep pattern matching wrong simplification

### ISSUE THREAD

**Issue by Gbury** [ocaml-flambda/ocaml#28]
In the following code using deep pattern matching:
```ocaml
type t =
  | Foo
  | Bar of t * string
  | Foobar of t * int
  | Foobabar of t * char
  | BarBar of t

let f = function
  | Foo ->
      print_endline "foo"
  | Bar ((Foobar _), _) ->
      print_endline "bar foobar"
  | Bar _ ->
      print_endline "bar"
  | Foobar _ ->
      print_endline "foobar"
  | Foobabar _ ->
      print_endline "foobabar"
  | BarBar _ ->
      print_endline "barbar"

let () =
  f (Bar (Foo, "hello world"))
```

It appears that the flambda2 simplifier erroneously removes a `Is_int` call in the case with the deep pattern matching, so that it directly tries and match the tag, which is incorrect since there are constructors without arguments (and thus no tag).

**Comment by mshinwell** [comment]
Can you try to reduce this to a smaller example?

**Comment by Gbury** [comment]
Actually, I tried and removing even one of the cases of the type makes it not fail (probably because it switched from a pattern matching to an series of if/then/else on small examples), so I don't think it's possible to have a smaller example.

**Comment by Gbury** [comment]
You can probably change the contents of the branches though (the segfault happens on the pattern matching part of the code), if it helps.

**Comment by Gbury** [comment]
Actually, the payload in the type are not necessary, so you can have the slightly smaller:
```ocaml
 type t =
  | Foo
  | Bar of t
  | Foobar of t
  | Foobabar of t
  | BarBar of t

let f = function
  | Foo ->
      print_endline "foo"
  | Bar Foobar _ ->
      print_endline "bar foobar"
  | Bar _ ->
      print_endline "bar"
  | Foobar _ ->
      print_endline "foobar"
  | Foobabar _ ->
      print_endline "foobabar"
  | BarBar _ ->
      print_endline "barbar"

let () =
  f (Bar Foo)
```
(the payloads were simply because the example was reduced from format.ml )

**Comment by chambart** [comment]
Minimized to
```OCaml
 type t =
  | Foo
  | Bar of t
  | Foobar of t
  | Foobabar of t

let f = function
  | Bar _ ->
    print_endline "bar"
  | _ ->
    print_endline "other"

let () =
  f (Foo)
```

I found the problem. I'm making a PR
